name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Accept licenses
      run: |
        yes | sdkmanager --licenses || true

    - name: Build with Gradle
      run: ./gradlew assembleUiOvpn23Release --no-daemon
      env:
        GRADLE_OPTS: "-Xmx4096m"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: build-UiOvpn23-release-apk
        path: main/build/outputs/apk/uiOvpn23/release/*.apk
